import { db, json, requireUser } from "../../../../lib/auth";
import { ensureDatabase } from "../../../../lib/database";

const text=(value:unknown)=>String(value??"").trim();
const rows=async<T>(sql:string)=>(await db().prepare(sql).all<T>()).results;

async function configuration(){
  const [categories,groups,teams,courts,days,staff,matches,finalLinks,settings]=await Promise.all([
    rows<any>("SELECT c.code,c.name,c.color,c.sort_order AS sortOrder,COALESCE(s.admission_method,'top2_each') AS admissionMethod,COALESCE(s.placement_mode,'top2') AS placementMode,COALESCE(s.entry_round,'semifinals') AS entryRound FROM categories c LEFT JOIN category_settings s ON s.category_code=c.code WHERE c.active=1 ORDER BY c.sort_order,c.code"),
    rows<any>("SELECT category_code AS categoryCode,code,name,sort_order AS sortOrder FROM tournament_groups ORDER BY category_code,sort_order,code"),
    rows<any>("SELECT code,name,category_code AS categoryCode,group_code AS groupCode FROM teams WHERE active=1 ORDER BY category_code,group_code,name"),
    rows<any>("SELECT code,name,sort_order AS sortOrder FROM courts WHERE active=1 ORDER BY sort_order,code"),
    rows<any>("SELECT code,name,day_date AS date,start_time AS startTime,end_time AS endTime,sort_order AS sortOrder FROM tournament_days ORDER BY sort_order,day_date"),
    rows<any>("SELECT name,can_referee AS canReferee,can_scorekeeper AS canScorekeeper,can_court_manager AS canCourtManager FROM staff WHERE active=1 ORDER BY name"),
    rows<any>("SELECT game_id AS gameId,category_code AS category,group_code AS groupCode,phase,match_date AS date,match_time AS time,court,home_ref AS homeRef,away_ref AS awayRef,scorekeeper,referee,court_manager AS courtManager,status FROM matches ORDER BY game_id"),
    rows<any>("SELECT target_game_id AS targetGameId,category_code AS categoryCode,section_title AS sectionTitle,section_order AS sectionOrder,target_order AS targetOrder,home_kind AS homeKind,home_ref AS homeRef,away_kind AS awayKind,away_ref AS awayRef FROM final_links ORDER BY category_code,section_order,target_order"),
    rows<{key:string;value:string}>("SELECT key,value FROM tournament_settings WHERE key='match_duration_minutes' OR key LIKE 'ui_%'"),
  ]);
  return {schemaVersion:1,exportedAt:new Date().toISOString(),organization:{name:"Polisportiva Intercomunale"},tournament:{name:"VolleyStars 2026",slug:"volleystars-2026",settings:Object.fromEntries(settings.map(item=>[item.key,item.value]))},categories,groups,teams,courts,days,staff,matches:matches.map(item=>({...item,status:item.date&&item.time&&item.court?"scheduled":"draft"})),finalLinks};
}

function validateConfig(value:any){
  const errors:string[]=[],warnings:string[]=[];if(!value||typeof value!=="object")return {errors:["Il file non contiene una configurazione valida."],warnings};if(value.schemaVersion!==1)errors.push("Versione del formato non supportata.");
  const required=["categories","groups","teams","courts","days","staff","matches","finalLinks"];for(const key of required)if(!Array.isArray(value[key]))errors.push(`Sezione ${key} mancante o non valida.`);if(errors.length)return {errors,warnings};
  const unique=(items:any[],key:string,label:string)=>{const seen=new Set<string>();for(const item of items){const id=text(item?.[key]);if(!id)errors.push(`${label}: codice mancante.`);else if(seen.has(id))errors.push(`${label}: codice ${id} duplicato.`);seen.add(id);}return seen;};
  const categories=unique(value.categories,"code","Categorie"),courts=unique(value.courts,"code","Campi"),days=unique(value.days,"code","Giornate"),games=unique(value.matches,"gameId","Gare"),teams=unique(value.teams,"code","Squadre"),groupKeys=new Set(value.groups.map((item:any)=>`${text(item.categoryCode)}|${text(item.code)}`));
  for(const item of value.groups)if(!categories.has(text(item.categoryCode)))errors.push(`Girone ${text(item.code)}: categoria inesistente.`);
  for(const item of value.teams){if(!categories.has(text(item.categoryCode)))errors.push(`Squadra ${text(item.code)}: categoria inesistente.`);if(item.groupCode&&!groupKeys.has(`${text(item.categoryCode)}|${text(item.groupCode)}`))errors.push(`Squadra ${text(item.code)}: girone inesistente.`);}
  for(const item of value.matches){if(!/^\d{4}$/.test(text(item.gameId)))errors.push(`Gara ${text(item.gameId)}: il codice deve avere quattro cifre.`);if(!categories.has(text(item.category)))errors.push(`Gara ${text(item.gameId)}: categoria inesistente.`);const allocated=Boolean(item.date||item.time||item.court);if(allocated&&(!/^\d{4}-\d{2}-\d{2}$/.test(text(item.date))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(text(item.time))||!courts.has(text(item.court))))errors.push(`Gara ${text(item.gameId)}: allocazione incompleta o campo inesistente.`);}
  for(const item of value.finalLinks){if(!games.has(text(item.targetGameId)))errors.push(`Collegamento finale: gara ${text(item.targetGameId)} inesistente.`);for(const side of ["home","away"]){const kind=text(item[`${side}Kind`]),ref=text(item[`${side}Ref`]);if((kind==="winner"||kind==="loser")&&!games.has(ref))errors.push(`Gara ${text(item.targetGameId)}: sorgente ${ref} inesistente.`);}}
  if(!value.categories.length)warnings.push("La configurazione non contiene categorie.");if(!value.matches.length)warnings.push("La configurazione non contiene gare.");const unallocated=value.matches.filter((item:any)=>!item.date||!item.time||!item.court).length;if(unallocated)warnings.push(`${unallocated} gare sono ancora da allocare.`);
  return {errors,warnings,summary:{categories:value.categories.length,groups:value.groups.length,teams:value.teams.length,courts:value.courts.length,days:value.days.length,matches:value.matches.length}};
}

export async function GET(request:Request){await ensureDatabase();if(!(await requireUser(request,["admin"])))return json({error:"Non autorizzato"},403);const body=JSON.stringify(await configuration(),null,2);return new Response(body,{headers:{"content-type":"application/json; charset=utf-8","content-disposition":`attachment; filename="VolleyStars-configurazione.volleystars.json"`,"cache-control":"no-store"}});}

export async function POST(request:Request){
  await ensureDatabase();if(!(await requireUser(request,["admin"])))return json({error:"Non autorizzato"},403);const payload=await request.json() as any,action=text(payload.action),config=payload.configuration,validation=validateConfig(config);if(validation.errors.length)return json({error:"La configurazione contiene errori.",...validation},400);if(action==="validate")return json({ok:true,message:"Configurazione valida e pronta per l’importazione.",...validation});if(action!=="apply")return json({error:"Operazione non valida."},400);
  const state=text((await db().prepare("SELECT value FROM tournament_settings WHERE key='tournament_state'").first<{value:string}>())?.value)||"planning";if(state!=="planning")return json({error:"La configurazione può essere sostituita soltanto mentre il torneo è in pianificazione."},409);const results=await db().prepare("SELECT COUNT(*) AS count FROM matches WHERE result<>'' OR set_1<>'' OR set_2<>'' OR set_3<>''").first<{count:number}>();if(Number(results?.count||0))return json({error:"Sono già presenti risultati: la configurazione strutturale non può più essere sostituita."},409);
  const statements=[db().prepare("DELETE FROM final_links"),db().prepare("DELETE FROM result_audit"),db().prepare("DELETE FROM matches"),db().prepare("DELETE FROM teams"),db().prepare("DELETE FROM tournament_groups"),db().prepare("DELETE FROM category_settings"),db().prepare("DELETE FROM categories"),db().prepare("DELETE FROM staff"),db().prepare("DELETE FROM tournament_days"),db().prepare("DELETE FROM courts")];
  for(const item of config.categories){statements.push(db().prepare("INSERT INTO categories(code,name,color,sort_order,active) VALUES(?,?,?,?,1)").bind(text(item.code),text(item.name),text(item.color)||"#dff4ea",Number(item.sortOrder)||0));statements.push(db().prepare("INSERT INTO category_settings(category_code,admission_method,placement_mode,entry_round) VALUES(?,?,?,?)").bind(text(item.code),text(item.admissionMethod)||"top2_each",text(item.placementMode)||"top2",text(item.entryRound)||"semifinals"));}
  for(const item of config.groups)statements.push(db().prepare("INSERT INTO tournament_groups(category_code,code,name,sort_order) VALUES(?,?,?,?)").bind(text(item.categoryCode),text(item.code),text(item.name),Number(item.sortOrder)||0));
  for(const item of config.teams)statements.push(db().prepare("INSERT INTO teams(code,name,category_code,group_code,active) VALUES(?,?,?,?,1)").bind(text(item.code),text(item.name),text(item.categoryCode),text(item.groupCode)));
  for(const item of config.courts)statements.push(db().prepare("INSERT INTO courts(code,name,sort_order,active) VALUES(?,?,?,1)").bind(text(item.code),text(item.name),Number(item.sortOrder)||0));
  for(const item of config.days)statements.push(db().prepare("INSERT INTO tournament_days(code,name,day_date,start_time,end_time,sort_order) VALUES(?,?,?,?,?,?)").bind(text(item.code),text(item.name),text(item.date),text(item.startTime)||"09:00",text(item.endTime)||"23:59",Number(item.sortOrder)||0));
  for(const item of config.staff)statements.push(db().prepare("INSERT INTO staff(name,can_referee,can_scorekeeper,can_court_manager,active) VALUES(?,?,?,?,1)").bind(text(item.name),item.canReferee?1:0,item.canScorekeeper?1:0,item.canCourtManager?1:0));
  for(const item of config.matches)statements.push(db().prepare("INSERT INTO matches(game_id,category_code,group_code,phase,match_date,match_time,court,home_ref,away_ref,scorekeeper,referee,court_manager,result,set_1,set_2,set_3,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'','','','',?)").bind(text(item.gameId),text(item.category),text(item.groupCode),text(item.phase)||"girone",text(item.date),text(item.time),text(item.court),text(item.homeRef),text(item.awayRef),text(item.scorekeeper),text(item.referee),text(item.courtManager),item.date&&item.time&&item.court?"scheduled":"draft"));
  for(const item of config.finalLinks)statements.push(db().prepare("INSERT INTO final_links(target_game_id,category_code,section_title,section_order,target_order,home_kind,home_ref,away_kind,away_ref) VALUES(?,?,?,?,?,?,?,?,?)").bind(text(item.targetGameId),text(item.categoryCode),text(item.sectionTitle)||"Fase finale",Number(item.sectionOrder)||0,Number(item.targetOrder)||0,text(item.homeKind),text(item.homeRef),text(item.awayKind),text(item.awayRef)));
  statements.push(db().prepare("INSERT INTO tournament_settings(key,value) VALUES('match_duration_minutes',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(text(config.tournament?.settings?.match_duration_minutes)||"70"),db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed','0') ON CONFLICT(key) DO UPDATE SET value='0'"),db().prepare("INSERT INTO tournament_settings(key,value) VALUES('tournament_state','planning') ON CONFLICT(key) DO UPDATE SET value='planning'"));await db().batch(statements);return json({ok:true,message:`Configurazione importata: ${config.matches.length} gare, ${config.teams.length} squadre e ${config.categories.length} categorie.`,...validation});
}
