import { db, json, requireUser } from "../../../../lib/auth";
import { ensureDatabase } from "../../../../lib/database";
import { dependencyOrderError, type ScheduleGroup } from "../../../../lib/schedule-dependencies";

const text=(value:unknown)=>String(value??"").trim();
type Match={gameId:string;category:string;groupCode:string;phase:string;date:string;time:string;court:string;homeRef:string;awayRef:string;referee:string;courtManager:string;result:string;status:string};
type Link={targetGameId:string;category:string;homeKind:string;homeRef:string;awayKind:string;awayRef:string};
const minutes=(value:string)=>{const [h,m]=value.split(":").map(Number);return h*60+m;};
const clock=(value:number)=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;
function placementOrder(match:Pick<Match,"phase"|"homeRef">){if(match.phase!=="finale")return -1;const places=(match.homeRef.match(/\d+/g)||[]).map(Number),key=`${places[0]||0}-${places[1]||0}`;return key==="7-8"?0:key==="5-6"?1:key==="3-4"?2:key==="1-2"?3:1;}
function sourceTokens(kind:string,ref:string,category:string,matches:Map<string,Match>,links:Map<string,Link>,seen:Set<string>):Set<string>{
  if(kind==="winner"||kind==="loser")return new Set([`outcome:${ref}:${kind}`]);const value=ref.toUpperCase();if(/^\d+$/.test(value))return new Set([`team:${value}`]);if(/^[A-Z][A-Z0-9_-]*\d+$/.test(value))return new Set([`rank:${category}:${value}`]);return new Set([`ref:${category}:${value}`]);
}
function matchTokens(gameId:string,matches:Map<string,Match>,links:Map<string,Link>,seen=new Set<string>()):Set<string>{
  if(seen.has(gameId))return new Set([`cycle:${gameId}`]);seen=new Set(seen);seen.add(gameId);const match=matches.get(gameId);if(!match)return new Set();const link=links.get(gameId);if(link)return new Set([...sourceTokens(link.homeKind,link.homeRef,match.category,matches,links,seen),...sourceTokens(link.awayKind,link.awayRef,match.category,matches,links,seen)]);return new Set([...sourceTokens("ref",match.homeRef,match.category,matches,links,seen),...sourceTokens("ref",match.awayRef,match.category,matches,links,seen)]);
}
function validate(rows:Match[],links:Map<string,Link>,duration:number){
  const matches=new Map<string,Match>(rows.map(item=>[item.gameId,item]));
  const active=rows.filter(item=>item.date&&item.time&&item.court);
  for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const a=active[i],b=active[j];if(a.date!==b.date||minutes(a.time)>=minutes(b.time)+duration||minutes(b.time)>=minutes(a.time)+duration)continue;if(a.court===b.court)return `Le gare ${a.gameId} e ${b.gameId} si sovrappongono sul campo ${a.court}.`;const ta=matchTokens(a.gameId,matches,links),tb=matchTokens(b.gameId,matches,links);if([...ta].some(value=>tb.has(value)))return `Una squadra risulta impegnata nelle gare ${a.gameId} e ${b.gameId}.`;const people=[a.referee,a.courtManager].filter(Boolean),busy=[b.referee,b.courtManager].find(value=>value&&people.includes(value));if(busy)return `${busy} risulta assegnato alle gare ${a.gameId} e ${b.gameId}.`;}
  return "";
}

function restCost(candidate:Match,scheduled:Match[],links:Map<string,Link>,duration:number){
  const combined=new Map<string,Match>([...scheduled,candidate].map(item=>[item.gameId,item])),tokens=matchTokens(candidate.gameId,combined,links);let cost=0;
  for(const token of tokens){const times=[...scheduled.filter(item=>item.date===candidate.date&&matchTokens(item.gameId,combined,links).has(token)).map(item=>minutes(item.time)),minutes(candidate.time)].sort((a,b)=>a-b),index=times.indexOf(minutes(candidate.time));let start=index,end=index;while(start>0&&times[start]-times[start-1]===duration)start--;while(end<times.length-1&&times[end+1]-times[end]===duration)end++;if(end-start+1>=3)return Number.POSITIVE_INFINITY;if((index>0&&times[index]-times[index-1]===duration)||(index<times.length-1&&times[index+1]-times[index]===duration))cost+=100;}
  const link=links.get(candidate.gameId),sourceIds=link?[link.homeKind==="winner"||link.homeKind==="loser"?link.homeRef:"",link.awayKind==="winner"||link.awayKind==="loser"?link.awayRef:""].filter(Boolean):[];
  for(const sourceId of sourceIds){const source=combined.get(sourceId);if(!source||source.date!==candidate.date||minutes(candidate.time)-minutes(source.time)!==duration)continue;const sourceLink=links.get(sourceId),previousIds=sourceLink?[sourceLink.homeKind==="winner"||sourceLink.homeKind==="loser"?sourceLink.homeRef:"",sourceLink.awayKind==="winner"||sourceLink.awayKind==="loser"?sourceLink.awayRef:""].filter(Boolean):[];if(previousIds.some(id=>{const previous=combined.get(id);return previous&&previous.date===source.date&&minutes(source.time)-minutes(previous.time)===duration;}))return Number.POSITIVE_INFINITY;}
  return cost;
}

export async function POST(request:Request){
  await ensureDatabase();if(!(await requireUser(request,["admin"])))return json({error:"Non autorizzato"},403);
  const payload=await request.json() as any,action=text(payload.action),state=text((await db().prepare("SELECT value FROM tournament_settings WHERE key='tournament_state'").first<{value:string}>())?.value)||"planning";
  if(action==="setState"){
    const next=text(payload.state),allowed=next==="planning"||state==="confirmed"&&next==="live"||state==="live"&&next==="closed"||state==="closed"&&next==="live";
    if(!allowed)return json({error:"Passaggio di stato non consentito."},409);
    if(next==="planning"&&state==="live"){const started=await db().prepare("SELECT COUNT(*) AS count FROM matches WHERE result<>'' OR set_1<>'' OR set_2<>'' OR set_3<>''").first<{count:number}>();if(Number(started?.count||0))return json({error:"Il torneo contiene già risultati: usa le correzioni operative senza riaprire la struttura."},409);}
    if(next==="closed"){const incomplete=await db().prepare("SELECT COUNT(*) AS count FROM matches WHERE result=''").first<{count:number}>();if(Number(incomplete?.count||0))return json({error:`Non puoi concludere il torneo: ${incomplete?.count} gare non hanno ancora un risultato finale.`},409);}
    await db().batch([db().prepare("INSERT INTO tournament_settings(key,value) VALUES('tournament_state',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(next),db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(next==="planning"?"0":"1")]);
    return json({ok:true,message:next==="planning"?"Pianificazione riaperta.":next==="live"?"Torneo in corso.":"Torneo concluso.",state:next});
  }
  if(state==="closed")return json({error:"Il torneo è concluso. Riaprilo prima di apportare modifiche."},409);
  if(["clearAll","autoAllocate","applyDay","confirmPlan"].includes(action)&&state!=="planning")return json({error:"Riapri la pianificazione prima di modificare il piano."},409);
  if(action==="clearAll"){if(text(payload.confirmation)!=="SVUOTA")return json({error:"Conferma non valida."},400);await db().batch([db().prepare("DELETE FROM final_links"),db().prepare("DELETE FROM result_audit"),db().prepare("DELETE FROM matches"),db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed','0') ON CONFLICT(key) DO UPDATE SET value='0'")]);return json({ok:true,message:"Tutte le gare sono state eliminate."});}
  if(action==="autoAllocate"){
    const [dayRows,courtRows,matchRows,linkRows,durationRow]=await Promise.all([
      db().prepare("SELECT code,day_date AS date,start_time AS startTime,end_time AS endTime,sort_order AS sortOrder FROM tournament_days ORDER BY sort_order,day_date").all<{code:string;date:string;startTime:string;endTime:string;sortOrder:number}>(),
      db().prepare("SELECT code,sort_order AS sortOrder FROM courts WHERE active=1 ORDER BY sort_order,code").all<{code:string;sortOrder:number}>(),
      db().prepare("SELECT game_id AS gameId,category_code AS category,group_code AS groupCode,phase,match_date AS date,match_time AS time,court,home_ref AS homeRef,away_ref AS awayRef,referee,court_manager AS courtManager,result,status FROM matches ORDER BY game_id").all<Match>(),
      db().prepare("SELECT target_game_id AS targetGameId,category_code AS category,home_kind AS homeKind,home_ref AS homeRef,away_kind AS awayKind,away_ref AS awayRef FROM final_links").all<Link>(),
      db().prepare("SELECT value FROM tournament_settings WHERE key='match_duration_minutes'").first<{value:string}>(),
    ]),days=dayRows.results,courts=courtRows.results,rows=matchRows.results as Match[],links=new Map<string,Link>(linkRows.results.map(item=>[item.targetGameId,item])),duration=Number(durationRow?.value||70);
    if(!days.length)return json({error:"Configura almeno una giornata prima dell’allocazione automatica."},409);if(!courts.length)return json({error:"Configura almeno un campo prima dell’allocazione automatica."},409);
    const targets=rows.filter(item=>!item.date||!item.time||!item.court),phaseOrder:Record<string,number>={girone:0,ottavi:1,quarti:2,"fase-finale":3,"finale-girone":4,finale:5};if(!targets.length)return json({ok:true,message:"Tutte le gare sono già allocate."});
    targets.sort((a,b)=>(phaseOrder[a.phase]??2)-(phaseOrder[b.phase]??2)||(a.phase==="finale"&&b.phase==="finale"?placementOrder(a)-placementOrder(b):0)||a.category.localeCompare(b.category)||a.gameId.localeCompare(b.gameId));
    const scheduled=rows.filter(item=>item.date&&item.time&&item.court),byId=new Map(rows.map(item=>[item.gameId,item])),categories=[...new Set(rows.map(item=>item.category))].sort(),preferredCourt=new Map(categories.map((category,index)=>[category,courts[index%courts.length].code])),categoryDayCount=new Map<string,number>(),courtDayCount=new Map<string,number>();
    for(const item of scheduled){categoryDayCount.set(`${item.category}|${item.date}`,(categoryDayCount.get(`${item.category}|${item.date}`)||0)+1);courtDayCount.set(`${item.court}|${item.date}`,(courtDayCount.get(`${item.court}|${item.date}`)||0)+1);}
    const dayIndex=new Map(days.map((item,index)=>[item.date,index])),stamp=(item:Pick<Match,"date"|"time">)=>(dayIndex.get(item.date)??999)*1440+minutes(item.time);
    for(const target of targets){let best:{match:Match;score:number}|null=null;const link=links.get(target.gameId),sourceIds=link?[link.homeKind==="winner"||link.homeKind==="loser"?link.homeRef:"",link.awayKind==="winner"||link.awayKind==="loser"?link.awayRef:""].filter(Boolean):[],sources=sourceIds.map(id=>byId.get(id)).filter(Boolean) as Match[],groupSources=target.phase!=="girone"?scheduled.filter(item=>item.category===target.category&&item.phase==="girone"):[],earlierPlacementFinals=target.phase==="finale"?scheduled.filter(item=>item.category===target.category&&item.phase==="finale"&&placementOrder(item)<placementOrder(target)):[],prerequisites=[...sources,...groupSources,...earlierPlacementFinals];if(sources.some(item=>!item.date||!item.time||!item.court))return json({error:`Non è possibile collocare la gara ${target.gameId} prima delle gare da cui dipende.`},409);const after=prerequisites.length?Math.max(...prerequisites.map(item=>stamp(item)+duration)):-1;
      for(const day of days){const start=minutes(day.startTime),end=minutes(day.endTime),slots=Math.max(0,Math.floor((end-start)/duration)),position=dayIndex.get(day.date)??0,phaseDayPenalty=500*(target.phase==="girone"?position:days.length-1-position);for(const court of courts)for(let slot=0;slot<slots;slot++){const candidate={...target,date:day.date,time:clock(start+slot*duration),court:court.code,status:"scheduled"},candidateStamp=stamp(candidate);if(candidateStamp<after)continue;const others=scheduled.filter(item=>item.gameId!==candidate.gameId),conflict=validate([...others,candidate],links,duration);if(conflict)continue;const rest=restCost(candidate,others,links,duration);if(!Number.isFinite(rest))continue;const dayLoad=categoryDayCount.get(`${candidate.category}|${candidate.date}`)||0,courtLoad=courtDayCount.get(`${candidate.court}|${candidate.date}`)||0,isPool=target.phase==="girone",courtPreference=candidate.court===preferredCourt.get(candidate.category)?0:isPool?40:8,timePriority=isPool?slot/100:slot*50,score=phaseDayPenalty+dayLoad*20+courtPreference+courtLoad*3+rest+timePriority;if(!best||score<best.score)best={match:candidate,score};}}
      if(!best)return json({error:`Non ho trovato uno spazio coerente per la gara ${target.gameId} entro gli orari configurati. Aumenta la fine attività, aggiungi una giornata o modifica le gare già allocate.`},409);scheduled.push(best.match);byId.set(best.match.gameId,best.match);categoryDayCount.set(`${best.match.category}|${best.match.date}`,(categoryDayCount.get(`${best.match.category}|${best.match.date}`)||0)+1);courtDayCount.set(`${best.match.court}|${best.match.date}`,(courtDayCount.get(`${best.match.court}|${best.match.date}`)||0)+1);
    }
    const groupRows=(await db().prepare("SELECT category_code AS category,code,sort_order AS sortOrder FROM tournament_groups").all<ScheduleGroup>()).results,dependency=dependencyOrderError(scheduled,linkRows.results,groupRows,duration);if(dependency)return json({error:dependency},409);
    const allocatedIds=new Set(targets.map(item=>item.gameId)),updates=scheduled.filter(item=>allocatedIds.has(item.gameId));await db().batch([...updates.map(item=>db().prepare("UPDATE matches SET match_date=?,match_time=?,court=?,status=CASE WHEN result<>'' THEN 'completed' ELSE 'scheduled' END WHERE game_id=?").bind(item.date,item.time,item.court,item.gameId)),db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed','0') ON CONFLICT(key) DO UPDATE SET value='0'")]);return json({ok:true,message:`Proposta creata: allocate ${updates.length} gare. Controllala e poi conferma il piano.`});
  }
  if(action==="confirmPlan"){
    const missing=await db().prepare("SELECT COUNT(*) AS count FROM matches WHERE status='draft' OR match_date='' OR match_time='' OR court=''").first<{count:number}>(),total=await db().prepare("SELECT COUNT(*) AS count FROM matches").first<{count:number}>(),unassigned=await db().prepare("SELECT COUNT(*) AS count FROM teams WHERE active=1 AND group_code=''").first<{count:number}>();
    if(!Number(total?.count||0))return json({error:"Genera prima le gare del torneo."},409);if(Number(unassigned?.count||0))return json({error:`Assegna prima tutte le squadre ai gironi (${unassigned?.count} mancanti).`},409);if(Number(missing?.count||0))return json({error:`Alloca prima tutte le gare (${missing?.count} incomplete).`},409);
    const categories=(await db().prepare("SELECT c.code,COALESCE(s.admission_method,'top2_each') AS admissionMethod,COALESCE(s.placement_mode,'top2') AS placementMode,COALESCE(s.entry_round,'semifinals') AS entryRound FROM categories c LEFT JOIN category_settings s ON s.category_code=c.code WHERE c.active=1").all<{code:string;admissionMethod:string;placementMode:string;entryRound:string}>()).results,groups=(await db().prepare("SELECT category_code AS category,code,name FROM tournament_groups").all<{category:string;code:string;name:string}>()).results,teams=(await db().prepare("SELECT category_code AS category,group_code AS groupCode FROM teams WHERE active=1").all<{category:string;groupCode:string}>()).results,scheduled=(await db().prepare("SELECT category_code AS category,group_code AS groupCode,phase,home_ref AS homeRef FROM matches").all<{category:string;groupCode:string;phase:string;homeRef:string}>()).results;
    for(const category of categories){const categoryGroups=groups.filter(group=>group.category===category.code);if(!categoryGroups.length)return json({error:`${category.code}: configura almeno un girone.`},409);const depth=category.admissionMethod==="top8_each"?8:category.admissionMethod==="top4_each"?4:2;for(const group of categoryGroups){const members=teams.filter(team=>team.category===category.code&&team.groupCode===group.code).length;if(members<2)return json({error:`${category.code} ${group.name}: servono almeno due squadre.`},409);if(category.admissionMethod.endsWith("_each")&&members<depth)return json({error:`${category.code} ${group.name}: servono almeno ${depth} squadre per l’ammissione scelta.`},409);const expected=members*(members-1)/2,actual=scheduled.filter(match=>match.category===category.code&&match.groupCode===group.code&&match.phase==="girone").length;if(actual<expected)return json({error:`${category.code} ${group.name}: genera prima tutte le gare del girone.`},409);}const finals=scheduled.filter(match=>match.category===category.code&&match.phase!=="girone");if(!finals.length)return json({error:`${category.code}: genera prima la fase finale.`},409);if(category.admissionMethod!=="winners_round_robin"){const qualified=category.admissionMethod==="winners_plus_best_second"?4:categoryGroups.length*depth,needed=category.entryRound==="round_of_16"?16:category.entryRound==="quarterfinals"?8:category.entryRound==="final"?2:category.placementMode==="top8"?8:4;if(qualified!==needed)return json({error:`${category.code}: il formato richiede ${needed} qualificate, ma la modalità ne produce ${qualified}.`},409);if(category.entryRound==="final"&&category.placementMode!=="top2")return json({error:`${category.code}: la finale diretta può determinare soltanto 1° e 2° posto.`},409);const labels=finals.map(match=>match.homeRef.toUpperCase()),required=category.placementMode==="top8"?["1° - 2°","3° - 4°","5° - 6°","7° - 8°"]:category.placementMode==="top4"?["1° - 2°","3° - 4°"]:["1° - 2°"];for(const label of required)if(!labels.some(value=>value.includes(label)))return json({error:`${category.code}: manca la finale ${label} prevista dalla categoria.`},409);}}
    const rows=(await db().prepare("SELECT game_id AS gameId,category_code AS category,group_code AS groupCode,phase,match_date AS date,match_time AS time,court,home_ref AS homeRef,away_ref AS awayRef,referee,court_manager AS courtManager,result,status FROM matches").all<Match>()).results as Match[],linkRows=(await db().prepare("SELECT target_game_id AS targetGameId,category_code AS category,home_kind AS homeKind,home_ref AS homeRef,away_kind AS awayKind,away_ref AS awayRef FROM final_links").all<Link>()).results as Link[],links=new Map<string,Link>(linkRows.map(item=>[item.targetGameId,item])),duration=Number((await db().prepare("SELECT value FROM tournament_settings WHERE key='match_duration_minutes'").first<{value:string}>())?.value||70),dayRows=(await db().prepare("SELECT day_date AS date,start_time AS startTime,end_time AS endTime,name FROM tournament_days").all<{date:string;startTime:string;endTime:string;name:string}>()).results,dayMap=new Map(dayRows.map(item=>[item.date,item])),outside=rows.find(item=>{const day=dayMap.get(item.date);return !day||minutes(item.time)<minutes(day.startTime)||minutes(item.time)+duration>minutes(day.endTime);});if(outside){const day=dayMap.get(outside.date);return json({error:day?`La gara ${outside.gameId} non rientra nell’orario ${day.startTime}–${day.endTime} di ${day.name}.`:`La gara ${outside.gameId} non appartiene a una giornata configurata.`},409);}const conflict=validate(rows,links,duration);if(conflict)return json({error:conflict},409);const dependency=dependencyOrderError(rows,linkRows,(await db().prepare("SELECT category_code AS category,code,sort_order AS sortOrder FROM tournament_groups").all<ScheduleGroup>()).results,duration);if(dependency)return json({error:dependency},409);
    await db().batch([db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed','1') ON CONFLICT(key) DO UPDATE SET value='1'"),db().prepare("INSERT INTO tournament_settings(key,value) VALUES('tournament_state','confirmed') ON CONFLICT(key) DO UPDATE SET value='confirmed'")]);return json({ok:true,message:"Piano validato e confermato. Ora puoi avviare il torneo."});
  }
  if(action==="bulkStaff"){
    const gameIds=[...new Set((Array.isArray(payload.gameIds)?payload.gameIds:[]).map(text).filter((item:string)=>/^\d{4}$/.test(item)))],staff=payload.staff&&typeof payload.staff==="object"?payload.staff:{},roles=[
      ["scorekeeper","can_scorekeeper","refertista"],["referee","can_referee","arbitro"],["courtManager","can_court_manager","responsabile di campo"],
    ] as const;
    if(!gameIds.length)return json({error:"Seleziona almeno una gara."},400);
    const changed=roles.filter(([key])=>Object.prototype.hasOwnProperty.call(staff,key));if(!changed.length)return json({error:"Scegli almeno un ruolo da modificare."},400);
    for(const [key,column,label] of changed){const name=text(staff[key]);if(name&&!(await db().prepare(`SELECT id FROM staff WHERE name=? AND ${column}=1 AND active=1`).bind(name).first()))return json({error:`${name} non è configurato come ${label}.`},400);}
    const placeholders=gameIds.map(()=>"?").join(","),selected=await db().prepare(`SELECT game_id AS gameId FROM matches WHERE game_id IN (${placeholders})`).bind(...gameIds).all<{gameId:string}>();if(selected.results.length!==gameIds.length)return json({error:"Una o più gare selezionate non esistono più."},409);
    const rows=(await db().prepare("SELECT game_id AS gameId,category_code AS category,phase,match_date AS date,match_time AS time,court,home_ref AS homeRef,away_ref AS awayRef,scorekeeper,referee,court_manager AS courtManager,result,status FROM matches").all<any>()).results,linkRows=(await db().prepare("SELECT target_game_id AS targetGameId,category_code AS category,home_kind AS homeKind,home_ref AS homeRef,away_kind AS awayKind,away_ref AS awayRef FROM final_links").all<Link>()).results,links=new Map<string,Link>(linkRows.map(item=>[item.targetGameId,item])),chosen=new Set(gameIds),simulated=rows.map(item=>chosen.has(item.gameId)?{...item,...Object.fromEntries(changed.map(([key])=>[key,text(staff[key])]))}:item),duration=Number((await db().prepare("SELECT value FROM tournament_settings WHERE key='match_duration_minutes'").first<{value:string}>())?.value||70),conflict=validate(simulated,links,duration);if(conflict)return json({error:conflict},409);
    const has=(key:string)=>changed.some(([item])=>item===key),statements=gameIds.map(gameId=>db().prepare("UPDATE matches SET scorekeeper=CASE WHEN ?=1 THEN ? ELSE scorekeeper END,referee=CASE WHEN ?=1 THEN ? ELSE referee END,court_manager=CASE WHEN ?=1 THEN ? ELSE court_manager END WHERE game_id=?").bind(has("scorekeeper")?1:0,text(staff.scorekeeper),has("referee")?1:0,text(staff.referee),has("courtManager")?1:0,text(staff.courtManager),gameId));if(state==="planning")statements.push(db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed','0') ON CONFLICT(key) DO UPDATE SET value='0'"));await db().batch(statements);
    return json({ok:true,message:`Staff aggiornato su ${gameIds.length} ${gameIds.length===1?"gara":"gare"}.`});
  }
  const day=await db().prepare("SELECT code,name,day_date AS date,start_time AS startTime,end_time AS endTime FROM tournament_days WHERE code=?").bind(text(payload.dayCode)).first<any>();if(!day)return json({error:"Seleziona una giornata valida."},400);
  const duration=Number((await db().prepare("SELECT value FROM tournament_settings WHERE key='match_duration_minutes'").first<{value:string}>())?.value||70);
  const rows=(await db().prepare("SELECT game_id AS gameId,category_code AS category,group_code AS groupCode,phase,match_date AS date,match_time AS time,court,home_ref AS homeRef,away_ref AS awayRef,referee,court_manager AS courtManager,result,status FROM matches").all<Match>()).results as Match[],linkRows=(await db().prepare("SELECT target_game_id AS targetGameId,category_code AS category,home_kind AS homeKind,home_ref AS homeRef,away_kind AS awayKind,away_ref AS awayRef FROM final_links").all<Link>()).results as Link[],links=new Map<string,Link>(linkRows.map(item=>[item.targetGameId,item])),groupRows=(await db().prepare("SELECT category_code AS category,code,sort_order AS sortOrder FROM tournament_groups").all<ScheduleGroup>()).results;
  if(action==="applyDay"){
    const lanes=payload.lanes&&typeof payload.lanes==="object"?payload.lanes:{},times=payload.times&&typeof payload.times==="object"?payload.times:{},courtRows=await db().prepare("SELECT code FROM courts WHERE active=1").all<{code:string}>(),validCourts=new Set(courtRows.results.map(item=>item.code)),seen=new Set<string>(),updates:{gameId:string;court:string;time:string}[]=[];
    for(const [court,value] of Object.entries(lanes)){if(!validCourts.has(court))return json({error:`Campo ${court} non valido.`},400);if(!Array.isArray(value))return json({error:"Pianificazione non valida."},400);for(const [index,idValue] of value.entries()){const gameId=text(idValue),supplied=text(times[gameId]),time=supplied||clock(minutes(day.startTime)+index*duration);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))return json({error:`Orario non valido per la gara ${gameId}.`},400);if(seen.has(gameId))return json({error:`La gara ${gameId} compare più volte.`},400);if(!rows.some(item=>item.gameId===gameId))return json({error:`Gara ${gameId} inesistente.`},400);seen.add(gameId);updates.push({gameId,court,time});}}
    const simulated=rows.map(item=>{const update=updates.find(row=>row.gameId===item.gameId);if(update)return {...item,date:day.date,time:update.time,court:update.court};if(item.date===day.date)return {...item,date:"",time:"",court:""};return item;}),warnings:string[]=[];
    for(const item of updates)if(minutes(item.time)<minutes(day.startTime)||minutes(item.time)+duration>minutes(day.endTime))warnings.push(`Gara ${item.gameId}: non rientra nell’orario ${day.startTime}–${day.endTime} di ${day.name}.`);const conflict=validate(simulated,links,duration);if(conflict)warnings.push(conflict);const dependency=dependencyOrderError(simulated,linkRows,groupRows,duration);if(dependency)warnings.push(dependency);
    const statements=[...updates.map(item=>db().prepare("UPDATE matches SET match_date=?,match_time=?,court=?,status=CASE WHEN result<>'' THEN 'completed' ELSE 'scheduled' END WHERE game_id=?").bind(day.date,item.time,item.court,item.gameId)),...rows.filter(item=>item.date===day.date&&!seen.has(item.gameId)).map(item=>db().prepare("UPDATE matches SET match_date='',match_time='',court='',status='draft' WHERE game_id=?").bind(item.gameId)),db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed','0') ON CONFLICT(key) DO UPDATE SET value='0'")];if(statements.length)await db().batch(statements);const message=warnings.length?`Bozza salvata con ${warnings.length} ${warnings.length===1?"avviso":"avvisi"}. Correggi le gare evidenziate prima di confermare il piano.`:"Pianificazione della giornata salvata. Conferma nuovamente il piano quando è completo.";return json({ok:true,message,warnings});
  }
  if(action==="shift"){
    const court=text(payload.court),source=rows.find(item=>item.gameId===text(payload.fromGameId));const delta=Number(payload.deltaMinutes);if(!source||source.date!==day.date||source.court!==court)return json({error:"Seleziona una gara della corsia."},400);if(!Number.isInteger(delta)||delta===0||Math.abs(delta)>360)return json({error:"Spostamento non valido."},400);const threshold=minutes(source.time),affected=rows.filter(item=>item.date===day.date&&item.court===court&&minutes(item.time)>=threshold);if(state==="live"&&affected.some(item=>item.status==="live"||item.status==="completed"))return json({error:"Durante il torneo non puoi spostare gare iniziate o concluse."},409);const shifted=affected.map(item=>({...item,time:clock(minutes(item.time)+delta)}));if(shifted.some(item=>minutes(item.time)<0||minutes(item.time)>=1440))return json({error:"Lo spostamento produce un orario non valido."},400);const simulated=rows.map(item=>shifted.find(row=>row.gameId===item.gameId)||item),warnings:string[]=[];for(const item of shifted)if(minutes(item.time)<minutes(day.startTime)||minutes(item.time)+duration>minutes(day.endTime))warnings.push(`Gara ${item.gameId}: non rientra nell’orario ${day.startTime}–${day.endTime} di ${day.name}.`);const conflict=validate(simulated,links,duration);if(conflict)warnings.push(conflict);const dependency=dependencyOrderError(simulated,linkRows,groupRows,duration);if(dependency)warnings.push(dependency);const statements=shifted.map(item=>db().prepare("UPDATE matches SET match_time=? WHERE game_id=?").bind(item.time,item.gameId));if(state==="planning")statements.push(db().prepare("INSERT INTO tournament_settings(key,value) VALUES('plan_confirmed','0') ON CONFLICT(key) DO UPDATE SET value='0'"));await db().batch(statements);const base=`Spostate ${affected.length} gare di ${delta>0?"+":""}${delta} minuti.`;return json({ok:true,message:warnings.length?`${base} Bozza salvata con ${warnings.length} ${warnings.length===1?"avviso":"avvisi"}; correggili prima della conferma.`:`${base}${state==="planning"?" Conferma nuovamente il piano.":""}`,warnings});
  }
  return json({error:"Operazione non valida."},400);
}
